version: '3.8'

services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    container_name: fastapi
    ports:
      - "8000:80"
    environment:
      - MODULE_NAME=app.main
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    networks:
      - app_net

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
