version: '3.8'

services:
  bot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
