services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Порт для доступа к веб-интерфейсу RabbitMQ
      - "5672:5672"    # Порт для обмена сообщениями
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Для сохранения данных между перезапусками

volumes:
  rabbitmq_data:
