"""Add updated_at column with default

Revision ID: 30cd37f3683f
Revises: c09f0aea00d1
Create Date: 2025-04-03 22:59:23.206137

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "30cd37f3683f"
down_revision: Union[str, None] = "c09f0aea00d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
