"""telegram id add

Revision ID: 68ecff2f281d
Revises: 6f39f71db803
Create Date: 2025-04-04 20:05:52.866630

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68ecff2f281d"
down_revision: Union[str, None] = "6f39f71db803"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "health",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.drop_constraint("health_user_id_fkey", "health", type_="foreignkey")
    op.create_foreign_key(
        None, "health", "users", ["user_id"], ["telegram_id"], ondelete="CASCADE"
    )
    op.alter_column(
        "nutrition",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.drop_constraint("nutrition_user_id_fkey", "nutrition", type_="foreignkey")
    op.create_foreign_key(
        None, "nutrition", "users", ["user_id"], ["telegram_id"], ondelete="CASCADE"
    )
    op.alter_column(
        "sleep",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.drop_constraint("sleep_user_id_fkey", "sleep", type_="foreignkey")
    op.create_foreign_key(
        None, "sleep", "users", ["user_id"], ["telegram_id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sleep", type_="foreignkey")
    op.create_foreign_key(
        "sleep_user_id_fkey", "sleep", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "sleep",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "nutrition", type_="foreignkey")
    op.create_foreign_key(
        "nutrition_user_id_fkey",
        "nutrition",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "nutrition",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "health", type_="foreignkey")
    op.create_foreign_key(
        "health_user_id_fkey",
        "health",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "health",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
