"""users goals fix

Revision ID: 7bff9c468956
Revises: 04256136803e
Create Date: 2025-04-08 17:03:50.703040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bff9c468956"
down_revision: Union[str, None] = "04256136803e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_goals", sa.Column("telegram_id", sa.BigInteger(), nullable=False)
    )
    op.drop_constraint("user_goals_user_telegram_id_key", "user_goals", type_="unique")
    op.create_unique_constraint(None, "user_goals", ["telegram_id"])
    op.drop_constraint(
        "user_goals_user_telegram_id_fkey", "user_goals", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "user_goals",
        "users",
        ["telegram_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    op.drop_column("user_goals", "user_telegram_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_goals",
        sa.Column("user_telegram_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user_goals", type_="foreignkey")
    op.create_foreign_key(
        "user_goals_user_telegram_id_fkey",
        "user_goals",
        "users",
        ["user_telegram_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "user_goals", type_="unique")
    op.create_unique_constraint(
        "user_goals_user_telegram_id_key", "user_goals", ["user_telegram_id"]
    )
    op.drop_column("user_goals", "telegram_id")
    # ### end Alembic commands ###
